create table userLogin(
	userId nvarchar not null,
	username varchar(50) not null,
	firstname nvarchar not null,
	lastname nvarchar not null,
	dob date not null,
	gentle nvarchar(5) not null,
	email varchar not null,
	topic1 nvarchar not null,
	question1 nvarchar not null,
	answer1 nvarchar not null,
	topic2 nvarchar,
	question2 nvarchar,
	answer2 nvarchar,
	topic3 nvarchar,
	question3 nvarchar,
	answer3 nvarchar,

	primary key (userId),
);