//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegisAndLogin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public string userId { get; set; }
        public string username { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public System.DateTime dob { get; set; }
        public string gentle { get; set; }
        public string email { get; set; }
        public string topic1 { get; set; }
        public string question1 { get; set; }
        public string answer1 { get; set; }
        public string topic2 { get; set; }
        public string question2 { get; set; }
        public string answer2 { get; set; }
        public string topic3 { get; set; }
        public string question3 { get; set; }
        public string answer3 { get; set; }
    }
}
